### ISSUE TITLE
Specify #pixels from the top and load in the upward direction as well

### ISSUE THREAD

**Issue by omanizer** [ElemeFE/vue-infinite-scroll#10]
Apple (and others), in all their wisdom, made it popular to have upward infinite scrolling text messaging apps.  It would be awesome to build a similar concept with this and be able to specify whether it was within X pixels from the top of the div and load more.

This could apply to viewing time-based logs where you could start off at one point in the middle of the log and then either scroll up or down and load more in either direction.

**Comment by Leopoldthecoder** [comment]
@ohmance Maybe you could try [this](https://github.com/ElemeFE/vue-loadmore)
