### ISSUE TITLE
下拉到底部无效，不会发起请求继续加载数据

### ISSUE THREAD

**Issue by i7eo** [ElemeFE/vue-infinite-scroll#127]
查看源代码后发现：`binding.value` 此时取不到传递过来的的函数名，显示undefined，
需要对源码下面俩处做修改：
1、`expression: binding.value`
改为：
`binding.expression`
2、
```
if (shouldTrigger && this.expression) {
    this.expression();
}
```
改为：
```
if (shouldTrigger && this.vm[this.expression]) {
    this.vm[this.expression]();
  }
```

**Comment by 17862974826** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
