### ISSUE TITLE
vue-infinite-scroll支持vue3吗

### ISSUE THREAD

**Issue by chaoqunzhan** [ElemeFE/vue-infinite-scroll#148]
在vue3中使用vue-infinite-scroll，loadmore没有反应，有人说不支持vue3，是不是真的不支持啊？

**Comment by nfhh** [comment]
不支持composition写法 这个包不维护了？

**Comment by chenxch** [comment]
可以注释 代码中 hook:mounted 相关部分代码

**Comment by ChristophWurst** [comment]
I've found https://www.npmjs.com/package/vue3-infinite-scroll, it could be a replacement but right now I can't get it to work either.

**Comment by dingshaohua-com** [comment]
看我的回答   
https://github.com/ElemeFE/vue-infinite-scroll/issues/159

**Comment by nsano-rururu** [comment]
@ChristophWurst 

https://www.npmjs.com/package/vue3-infinite-scroll
>Security holding package
This package contained malicious code and was removed from the registry by the npm security team. A placeholder was published to ensure users are not affected in the future.
>
>Please refer to www.npmjs.com/advisories?search=vue3-infinite-scroll for more information.

**Comment by nsano-rururu** [comment]
https://www.npmjs.com/package/v3-infinite-loading

**Comment by chaoqunzhan** [comment]
自己写了个 
https://juejin.cn/post/7032186033101864973

**Comment by chaoqunzhan** [comment]
> 在vue3中使用vue-infinite-scroll，loadmore没有反应，有人说不支持vue3，是不是真的不支持啊？
