### ISSUE TITLE
使用指令实现会有一点问题

### ISSUE THREAD

**Issue by banricho** [ElemeFE/vue-infinite-scroll#20]
这个问题主要出在 Vue，指令的 `bind` / `unbind` 钩子只会在所属组件 `ready` / `destroyed` 时触发，当使用 `keep-alive` 的时候，问题来了。

DEMO：https://jsfiddle.net/banricho/jrchrxp9/

在这个插件上的体现就是，当组件被 `keep-alive` 挂起，滚动时依然在触发事件。

**Comment by banricho** [comment]
刚刚翻了下以前的 issue，原来是已知问题 -。-

**Comment by furybean** [comment]
刚想起来 mint 的 loadmore 也可以坐这个功能，而且是组件：https://github.com/ElemeFE/mint-ui

**Comment by banricho** [comment]
我也写了个类似的组件：https://github.com/banricho/Element/tree/master/src/Lazy
代码比较丑。。。
