### ISSUE TITLE
当前页面数据从有变为空后加载报错

### ISSUE THREAD

**Issue by one-meter** [ElemeFE/vue-infinite-scroll#22]
需要加载数据的页面 部分代码：
`<div v-if="tempUserOrderList1.length > 0" class="aui-content">
        <ul class="aui-list-view" v-infinite-scroll="loadMore1()" infinite-scroll-disabled="loading1" infinite-scroll-distance="10">
            <li v-for="s in tempUserOrderList1" class="aui-list-view-cell aui-img">
                   //........
            </li>
     </ul>
</div>
<div v-else class="aui-content">
     <ul class="aui-list-view">
         <li class="aui-list-view-cell aui-img">
                  到目前还没有待付款的订单！
        </li>
     </ul>
 </div>`

当tempUserOrderList1有且只有一条数据时，页面操作数据后，重新加载变为0，报错：
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
vue.common.js?1090:3337
导致当前页面卡死，不能点击。

去掉v-infinite-scroll loadMore相关代码后正常。

请大神看看什么问题，如何解决？ 跪谢！~

**Comment by one-meter** [comment]
。。。无法排版。差评！

**Comment by Leopoldthecoder** [comment]
请在 `ul` 元素上添加 `infinite-scroll-immediate-check="false"`

**Comment by one-meter** [comment]
问题完美解决！楼上的大神你棒棒哒~！给你一年365个赞，剩一天让你骄傲！
