### ISSUE TITLE
在ajax回调中改变infinite-scroll-disabled的值，无效

### ISSUE THREAD

**Issue by vancezhu** [ElemeFE/vue-infinite-scroll#25]
在ajax回调中改变infinite-scroll-disabled的值，无效。
如果是文档说明中的，set time out 中设置是可以的。

**Comment by Leopoldthecoder** [comment]
拿文档来说，流程是：
1、滚动到距离底部 `infinite-scroll-distance` 的范围内
2、检查 `infinite-scroll-disabled` 是否为真，若不为真则执行加载。由于 `busy` 初始值为 `false`，所以执行加载
3、执行 `loadMore`，`busy` 被赋值为 `true`。注意，这时 `loadMore` 会继续执行，而这里把 `busy` 赋值为 `true` 的意义是，确保此时若再次滚动屏幕进入 `infinite-scroll-distance` 的范围内不再执行 `loadMore`（参考步骤 2）
4、一秒后加载完成，`busy` 被赋值为 `false`，这样再次触发步骤 2 时就可以再次执行 `loadMore`
综上，若在 ajax 回调中改变 `infinite-scroll-disabled` 的值，此次回调会继续执行，只是 `infinite-scroll-disabled` 为真的这段时间内不会再次触发回调。
