### ISSUE TITLE
works great on desktop, not reload on mobile

### ISSUE THREAD

**Issue by tzookb** [ElemeFE/vue-infinite-scroll#30]
Implemented the code, and it worked great on desktop, but when I use it with my phone, it doesnt fires the load more event....

any ideas?

**Comment by Leopoldthecoder** [comment]
Could you provide specific code?

**Comment by TIGERB** [comment]
It worked for me, for exmaple, http://tigerb.github.io/easy-vue/

**Comment by tzookb** [comment]
Thanks works great, sorry you are awesome
