### ISSUE TITLE
为什么我用require引进的话，bind里的this 是undefined

### ISSUE THREAD

**Issue by yangbys** [ElemeFE/vue-infinite-scroll#33]
![image](https://cloud.githubusercontent.com/assets/5164085/19258380/f8211eec-8fa9-11e6-81f7-bcbe2cc4edd9.png)

![image](https://cloud.githubusercontent.com/assets/5164085/19258330/8ce417ba-8fa9-11e6-833b-2dedae296530.png)

我用的是 vue2.0
![image](https://cloud.githubusercontent.com/assets/5164085/19258346/a719ac8a-8fa9-11e6-8efc-c88b000a0382.png)

会报这个错~~到底是什么原因呢

**Comment by Leopoldthecoder** [comment]
使用 Vue 2.0 的话，请使用 mint-ui@next 里的 vue-infinite-scroll。本仓库目前只支持 Vue 1.0.x，等 mint-ui 发布正式版时会同步更新本仓库。
