### ISSUE TITLE
TypeError: Cannot read property 'context' of undefined

### ISSUE THREAD

**Issue by ndelvalle** [ElemeFE/vue-infinite-scroll#44]
Im getting the following error: `TypeError: Cannot read property 'context' of undefined`. Is this related to my vuejs version? (Im using vue 1).

Does this lib supports vue2 only? What npm version do I have to point to get the vuejs1 support?

Thanks in advanced!

**Comment by Leopoldthecoder** [comment]
0.2.3

**Comment by ndelvalle** [comment]
Can you publish that to `npm`? The current version is `2.0.0`
