### ISSUE TITLE
Getting TypeError: Cannot read property 'removeEventListener' of undefined

### ISSUE THREAD

**Issue by kojilab** [ElemeFE/vue-infinite-scroll#46]
I'm getting the error above and the console it happens here. Am I missing something in my code?
Thanks

```
unbind: function unbind(el) {
      el[ctx].scrollEventTarget.removeEventListener('scroll', el[ctx].scrollListener);
    }
```

**Comment by kojilab** [comment]
Bad markup I believe

**Comment by itstyro** [comment]
Hi @kojilab ,

I am facing the exact same issue ! I checked my markup. Each markup element has a closing tag. is there something else that could be wrong with the markup ?

**Comment by itstyro** [comment]
I had Infinite scroll attributes on the element where my v-for resides and had some filters that changes the DOM elements. 

 I just moved the Infinite scroll attributes to a parent div element and now it works fine !!

Thanks for the clue @kojilab .

**Comment by kojilab** [comment]
That's what I did thinking it was the markup but moving it was the key.
