### ISSUE TITLE
指定滚动的方向

### ISSUE THREAD

**Issue by tiaod** [ElemeFE/vue-infinite-scroll#52]
可以实现 向上滚动加载更多 么？例如聊天记录查询，向上滚动查看更多聊天记录

**Comment by Leopoldthecoder** [comment]
不能

**Comment by tiaod** [comment]
没有计划实现这个？

**Comment by tiaod** [comment]
找到了
https://github.com/PeachScript/vue-infinite-loading
https://github.com/egoist/vue-mugen-scroll
