### ISSUE TITLE
其他组件内部使用infinite-scroll失效

### ISSUE THREAD

**Issue by NexusLee** [ElemeFE/vue-infinite-scroll#57]
因为遍历的是组件 这种情况该如何处理

**Comment by furybean** [comment]
可以提供个可重现 demo 么？

**Comment by hong-xu** [comment]
使用infinite-scroll插件拉到底部，不能触发v-infinite-scroll="loadMore"绑定的loadMore事件

**Comment by NexusLee** [comment]
我刚试着写了个demo，虽然loadmore这个方法会执行很多遍，但是确实可以执行了，猜测我的问题是可能布局引起的
