### ISSUE TITLE
Reverse scroll

### ISSUE THREAD

**Issue by kuceram** [ElemeFE/vue-infinite-scroll#64]
In our project, we need to implement reverse scroll: we load data from bottom up and if you scroll up you get the results.

It would be nice to have this feature in infinite scroll...

**Comment by marcoocram** [comment]
any plans to implement this?

thanks!

**Comment by evanoxu** [comment]
@kuceram try [this](https://github.com/mint-ui/mint-loadmore) .

**Comment by kuceram** [comment]
We finally decided to use [vue-infinite-loading](https://github.com/PeachScript/vue-infinite-loading) plugin and it works. Thanks for suggestions...
