### ISSUE TITLE
keep-alive组件内跨页面会导致前一个页面的无限滚动触发

### ISSUE THREAD

**Issue by kimixu717** [ElemeFE/vue-infinite-scroll#68]
如题

**Comment by Diamondjcx** [comment]
同一个页面多个tab页签，来回切换也触发

**Comment by zhongxiaopang** [comment]
Dom结构中infinite-scroll-disabled="loading"，可以用vuex全局定义loading的值，哪个页面用自己的loading值来控制是否滚动加载，如果tab很多，不建议使用这个滚动加载，移动端最好用手势滑动去加载更多数据。

**Comment by huilang-me** [comment]
@zhongxiaopang 请问您说的手势滑动具体指的是？

**Comment by zhongxiaopang** [comment]
@Diamondjcx 就是普遍的下拉刷新和上拉加载啊，mint-ui中事有demo的，可以看下代码。

**Comment by kx59717** [comment]
已弃坑,改用vue-infinite-loading了,很好用

**Comment by yf900914** [comment]
用vue-infinite-loading也会在页面切换时页面会无限滚动
