### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by aios** [ElemeFE/vue-infinite-scroll#8]
Have you an example app - for look realised infinite scroll?

**Comment by obingo** [comment]
It's so easy to learn from [example/index.html](https://github.com/ElemeFE/vue-infinite-scroll/blob/master/example/index.html)

**Comment by nerdyglasses** [comment]
Doesn't work for me as well. The `doCheck` function won't be called.

**Comment by furybean** [comment]
@Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
@nerdyglasses Could you provide an online demo?

**Comment by nerdyglasses** [comment]
Unfortunately I'm not able to create an online demo. But this is my code.

I've added a `console.log('binding')` to the `bind: function bind()` function to see if it will be called. Nothing happens.

I've added another `console.log('evaluating')` right above the throttle function to check if it will be evaluated. It will be.

```
<template>
  <div class="unique-ids-modal">
    <white-modal-view headline="Unique IDs" v-ref:modal>
      <ul class="unique-ids"
          v-infinite-scroll="fetchNext()"
          :infinite-scroll-disabled="loading"
          :infinite-scroll-distance="30">
        <li class="unique-id" v-for="uniqueId in uniqueIds">{{ uniqueId.uuid }}</li>
      </ul>
    </white-modal-view>
  </div>
</template>

<script>
import infiniteScroll from 'vue-infinite-scroll'
import WhiteModalView from './WhiteModalView'

export default {
  name: 'UniqueIdsModalView',

  directives: {
    infiniteScroll
  },

  components: {
    WhiteModalView
  },

  data () {
    return {
      loading: false,
      count: 0,
      next_page: true,
      page: 1,
      uniqueIds: []
    }
  }
}
</script>

<style lang="sass">

.unique-ids-modal

  .unique-ids
    height: 200px
    overflow: auto

</style>

```

**Comment by nerdyglasses** [comment]
PS. I've removed a bunch of code here. Assume that the `findMore` method exists.

**Comment by Leopoldthecoder** [comment]
OK. Will get back to you after I test this.

**Comment by nerdyglasses** [comment]
okay white modal view is just a component with a slot.

**Comment by Leopoldthecoder** [comment]
Hi @nerdyglasses, at the top of your script, change
```javascript
import infiniteScroll from 'vue-infinite-scroll'
```
to
```javascript
import { infiniteScroll } from 'vue-infinite-scroll'
```
or 
```javascript
var infiniteScroll = require('vue-infinite-scroll').infiniteScroll
```
`vue-infinite-scroll` exports an object and what you need is the `infiniteScroll` part. See [here](https://github.com/ElemeFE/vue-infinite-scroll/blob/master/src/index.js#L13).

**Comment by nerdyglasses** [comment]
@Leopoldthecoder My mistake. I should have seen this. It works well now. Thx for helping me out.

**Comment by Leopoldthecoder** [comment]
@nerdyglasses No problem.

**Comment by VictorPulzz** [comment]
In my code this dont work 
![image](https://user-images.githubusercontent.com/23406402/77404296-8e7f1e80-6dc2-11ea-859a-949228632b0e.png)

loadDisable have true value. And when I scroll nothing happens!!!
My imports: 
`import infiniteScroll from 'vue-infinite-scroll'
Vue.use(infiniteScroll)`
