### ISSUE TITLE
Trigger loadmore only on scroll bottom

### ISSUE THREAD

**Issue by Mdpproduction** [ElemeFE/vue-infinite-scroll#9]
Hi, thanks for the plugin,
but i need to know if it's possible to trigger the loadMore content, only when i'm scrolling to the bottom, and not on top. Or maybe i'm not understanding how it works the trigger.

**Comment by furybean** [comment]
If you do not want loadMore when component ready, you should set infinite-scroll-immediate-check="false".

**Comment by Mdpproduction** [comment]
Thanks man
